name: "Generate Zod bindings module"
description: "generates a ESM module of Zod bindings"
inputs:
  schema_dir:
    description: "The directory where the schema is located in this repo"
    required: true
  token:
    description: "The github token"
    required: true
  target_repo:
    description: "The target repo for the build"
    required: true
  target_branch:
    description: "The target branch for the build"
    required: false
runs:
  using: "node20"
  main: "index.js"
